// src/utils/newsData.js

export const NEWS = [
  { id:1,  t:"BI Tahan Suku Bunga di Level 6.25%", sentiment:"bullish", c:"MAKRO",
    b:"Rapat Dewan Gubernur memutuskan mempertahankan BI Rate demi stabilitas nilai tukar rupiah." },
  { id:2,  t:"Inflasi Bulan Ini Melonjak Tajam Mencapai 8%, Jauh di Atas Ekspektasi.", sentiment:"bearish", c:"MAKRO",
    b:"Harga barang mahal, daya beli masyarakat turun, laba perusahaan berpotensi anjlok." },
  { id:3,  t:"Laba Bersih PT Maju Mundur (Maju) Meroket 150% di Kuartal III.", sentiment:"bullish", c:"KORPORASI",
    b:"Kinerja fundamental perusahaan sangat sehat, investor akan berlomba membeli saham ini." },
  { id:4,  t:"Skandal Korupsi! Direktur Utama PT Angin Ribut Ditangkap KPK.", sentiment:"bearish", c:"KORPORASI",
    b:"Terjadi krisis kepercayaan (trust issue). Investor panik dan melakukan jual rugi (panic selling)." },
  { id:5,  t:"PT Cuan Selalu Bagikan Dividen Jumbo dengan Yield 10%.", sentiment:"bullish", c:"KORPORASI",
    b:"Investor menyukai pendapatan pasif (dividen). Permintaan saham akan naik sebelum tanggal pembagian (cum date)." },
  { id:6,  t:"Pabrik Utama PT ABC Terbakar Hebat, Operasional Berhenti Total.", sentiment:"bearish", c:"KORPORASI",
    b:"Proses produksi terhenti, target pendapatan pasti tidak tercapai. Sentimen sangat negatif." },
  { id:7,  t:"Perusahaan Meresmikan Pergantian Logo Baru dan Tagline.", sentiment:"neutral", c:"KORPORASI",
    b:"Hanya perubahan branding, tidak ada pengaruh langsung terhadap laba atau arus kas perusahaan." },
  { id:8,  t:"Harga Komoditas Batu Bara Global Cetak Rekor Tertinggi Baru.", sentiment:"bullish", c:"KOMODITAS",
    b:"Perusahaan batu bara akan mendapat untung besar karena harga jual produk mereka meroket." },
  { id:9,  t:"Pemerintah Sahkan Aturan Pengetatan Ekspor, Pajak Dinaikkan 15%.", sentiment:"bearish", c:"KEBIJAKAN",
    b:"Beban perusahaan bertambah, margin keuntungan menjadi lebih tipis." },
  { id:10, t:"PT Sukses Makmur Berhasil Akuisisi Perusahaan Saingannya.", sentiment:"bullish", c:"KORPORASI",
    b:"Perusahaan menghilangkan kompetitor dan memonopoli pasar, proyeksi laba masa depan meningkat." },
  { id:11, t:"RUPS Menyetujui Pergantian Susunan Komisaris.", sentiment:"neutral", c:"KORPORASI",
    b:"Rotasi wajar dalam perusahaan, kecuali komisaris baru membawa kasus buruk. Biasanya pasar tidak merespon berlebihan." },
  { id:12, t:"Terlilit Hutang, PT X Gagal Bayar Bunga Obligasi Jatuh Tempo.", sentiment:"bearish", c:"KORPORASI",
    b:"Risiko kebangkrutan (default). Harga saham bisa anjlok hingga batas bawah (ARB)." },
  { id:13, t:"Laporan Pekerjaan AS: Pengangguran Turun, Ekonomi Menguat.", sentiment:"bullish", c:"GLOBAL",
    b:"Ekonomi global membaik, berdampak positif pada sentimen bursa di berbagai negara termasuk IHSG." },
  { id:14, t:"Rumor di Grup Telegram: PT Y Akan Dibeli oleh Konglomerat Asing.", sentiment:"neutral", c:"KORPORASI",
    b:"Masih rumor tanpa bukti kuat (unverified news). Bisa dimanfaatkan speculator sesaat, tapi rawan bantahan." },
  { id:15, t:"Pemerintah Memberikan Insentif Pajak 0% untuk Pembelian Properti.", sentiment:"bullish", c:"KEBIJAKAN",
    b:"Penjualan rumah akan naik drastis, menguntungkan emiten/perusahaan properti dan perbankan." },
  { id:16, t:"Hari Libur Nasional Bergeser, Perdagangan Bursa Libur 1 Hari.", sentiment:"neutral", c:"DOMESTIK",
    b:"Libur bursa tidak mengubah nilai atau fundamental perusahaan sama sekali." },
  { id:17, t:"Tensi Geopolitik Memanas, Perang Meletus di Negara Penghasil Minyak.", sentiment:"bearish", c:"GLOBAL",
    b:"Perang memicu ketidakpastian (FUD). Investor akan menarik dana dari saham ke instrumen aman seperti emas." },
  { id:18, t:"Perusahaan Rilis Laporan Program CSR (Tanam 1000 Pohon).", sentiment:"neutral", c:"KORPORASI",
    b:"Bagus untuk citra lingkungan hidup perusahaan (ESG), namun dampak pada kenaikan saham harian sangat minim." },
  { id:19, t:"Rilis Produk Baru PT Z Gagal Total di Pasaran, Ditarik dari Toko.", sentiment:"bearish", c:"KORPORASI",
    b:"Kerugian dari biaya riset dan produksi, hilangnya potensi pendapatan di kuartal berikutnya." },
  { id:20, t:"Emiten Teknologi Mengumumkan Rencana Buyback (Pembelian Kembali) Saham.", sentiment:"bullish", c:"KORPORASI",
    b:"Perusahaan merasa harga sahamnya terlalu murah di pasar dan punya kas berlebih. Menunjukkan sinyal percaya diri." },
];